groups:
  - name: services-health
    rules:
      - alert: HighErrorRate
        expr: rate(http_server_requests_seconds_count{status=~"5.."}[1m]) > 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Servicio devolviendo errores 5xx"
          description: "El servicio {{ $labels.instance }} est√° devolviendo errores 5xx."
