spring:
  application:
    name: notification-orchestrator
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: securepass
    virtual-host: /
  cloud:
    consul:
      enabled: true
      host: ${CONSUL_HOST:consul}
      port: ${CONSUL_PORT:8500}
      discovery:
        enabled: true
        service-name: orchestrator-service
        instance-id: ${spring.application.name}:${random.value}
        health-check-path: /actuator/health
        health-check-interval: 10s
        prefer-ip-address: false
        hostname: notiorchestrator
    
server:
  port: 8080

orchestrator:
  exchange: auth.events
  queues:
    input: orchestrator.queue
  routing-keys:
    user: "user.*"
    password: "password.*"
    send-email: "send.email"
    send-sms: "send.sms"

logging:
  level:
    com.microservicios.orchestrator: DEBUG
    org.springframework.amqp: DEBUG
    root: INFO
